###
POST https://project08.site/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

    mutation updateUser($updateUserInput: updateUserInput!){
        updateUser(updateUserInput:$updateUserInput){
          userId
        }
    }

{
    updateUserInput:{
            "noticeTitle": "data.title",
            "noticeContents": "data.boardContents",
            "noticeCategory" : "data.category",
            "url": ["www.naver.com"]
    }

}  

###
http://localhost:3000/users/09bcd934-5c70-4d1f-925a-9c2d94c17b94

###
http://localhost:3000/uesrs/014f78b0-56a1-4e0c-be28-d0f3d0161753